name: festeasy_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  app_links: ^6.0.0
  bloc: ^9.0.0
  dio: ^5.0.0
  drift: ^2.0.0
  drift_flutter: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.2
  google_fonts: ^6.0.0
  image_picker: ^1.2.1
  intl: ^0.20.0
  path_provider: ^2.0.0
  supabase_flutter: ^2.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.3
  drift_dev: ^2.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  mocktail: ^1.0.0
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/proveedores/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-icon.png"
