name: festeasy_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  dio: ^5.9.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.2
  intl: ^0.20.2
  supabase_flutter: ^2.10.3
  uni_links: ^0.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  drift_dev: ^2.29.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-icon.png"
